# Generated by Django 4.2.1 on 2023-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200, verbose_name='Tarixiy')),
                ('uzbek', models.CharField(max_length=200, verbose_name='Zamonaviy')),
            ],
        ),
        migrations.DeleteModel(
            name='Dict',
        ),
    ]
