# Generated by Django 4.2.1 on 2023-07-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_history_delete_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='english',
            new_name='tarixiy',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='uzbek',
            new_name='zamonaviy',
        ),
    ]
